from __future__ import annotations

DISCOVERY_TOPICS: tuple[str, ...] = (
    "adolescent mental health",
    "anxiety",
    "depression",
    "stress",
    "burnout",
    "loneliness",
    "grief",
    "emotional regulation",
    "exam stress",
    "school refusal",
    "school avoidance",
    "performance anxiety",
    "bullying",
    "cyberbullying",
    "peer pressure",
    "social isolation",
    "friendship issues",
    "aggression",
    "anger",
    "risk taking",
    "adhd",
    "autism",
    "learning difficulties",
    "sleep",
    "physical activity",
    "nutrition",
    "digital wellness",
    "screen time",
    "gaming addiction",
    "internet addiction",
    "self harm",
    "suicide prevention",
    "substance abuse",
    "vaping",
    "alcohol abuse",
    "life skills",
    "communication skills",
    "decision making",
    "emotional intelligence",
    "problem solving",
    "resilience",
    "self awareness",
    "mental health",
    "school wellbeing",
    "teacher training",
    "parent education",
    "adolescent health",
)

TOPIC_ALIASES: dict[str, tuple[str, ...]] = {
    "adolescent mental health": ("adolescent mental health", "youth mental health", "teen mental health"),
    "anxiety": ("anxiety", "worry", "panic"),
    "depression": ("depression", "low mood"),
    "stress": ("stress", "exam stress", "academic stress"),
    "burnout": ("burnout", "exhaustion"),
    "loneliness": ("loneliness", "lonely"),
    "grief": ("grief", "bereavement", "loss"),
    "emotional regulation": ("emotional regulation", "emotion regulation", "self regulation"),
    "exam stress": ("exam stress", "test anxiety", "examination stress"),
    "school refusal": ("school refusal", "school refusal behavior", "refusing school"),
    "school avoidance": (
        "school avoidance",
        "school absenteeism",
        "attendance avoidance",
        "chronic absenteeism",
        "school attendance",
        "student attendance",
    ),
    "performance anxiety": ("performance anxiety", "stage fright", "evaluation anxiety"),
    "bullying": ("bullying", "peer violence"),
    "cyberbullying": ("cyberbullying", "online bullying", "digital safety"),
    "peer pressure": ("peer pressure", "peer influence"),
    "social isolation": ("social isolation", "social withdrawal"),
    "friendship issues": ("friendship issues", "friendship problems", "peer relationships"),
    "aggression": ("aggression", "aggressive behavior"),
    "anger": ("anger", "anger management"),
    "risk taking": ("risk taking", "risk-taking", "risky behavior"),
    "adhd": ("adhd", "attention deficit", "hyperactivity"),
    "autism": ("autism", "autism spectrum", "asd"),
    "learning difficulties": ("learning difficulties", "learning disability", "specific learning disorder"),
    "sleep": ("sleep", "sleep hygiene", "insomnia"),
    "physical activity": ("physical activity", "exercise", "movement"),
    "nutrition": ("nutrition", "diet", "healthy eating"),
    "digital wellness": (
        "digital wellness",
        "digital wellbeing",
        "digital well-being",
        "digital citizenship",
        "healthy technology use",
        "online safety",
        "media balance",
    ),
    "screen time": (
        "screen time",
        "screen-time",
        "media use",
        "device use",
        "technology use",
    ),
    "gaming addiction": ("gaming addiction", "gaming disorder", "problem gaming"),
    "internet addiction": ("internet addiction", "problematic internet use"),
    "self harm": ("self harm", "self-harm", "self injury", "self-injury"),
    "suicide prevention": ("suicide prevention", "suicidal ideation", "suicide risk"),
    "substance abuse": ("substance abuse", "substance use", "alcohol", "tobacco", "drugs"),
    "vaping": ("vaping", "e-cigarette", "electronic cigarette"),
    "alcohol abuse": ("alcohol abuse", "alcohol misuse", "underage drinking"),
    "life skills": (
        "life skills",
        "social emotional learning",
        "social-emotional learning",
        "sel framework",
        "self management",
        "self-management",
        "social awareness",
    ),
    "communication skills": (
        "communication skills",
        "effective communication",
        "active listening",
        "interpersonal communication",
        "relationship skills",
    ),
    "decision making": (
        "decision making",
        "decision-making",
        "responsible decision making",
        "responsible decision-making",
        "making decisions",
    ),
    "emotional intelligence": (
        "emotional intelligence",
        "emotional literacy",
        "understanding emotions",
        "emotional competence",
    ),
    "problem solving": (
        "problem solving",
        "problem-solving",
        "conflict resolution",
        "solving problems",
    ),
    "resilience": (
        "resilience",
        "resilient",
        "coping skills",
        "protective skills",
    ),
    "self awareness": (
        "self awareness",
        "self-awareness",
        "self knowledge",
        "self-knowledge",
        "recognizing emotions",
    ),
    "mental health": ("mental health", "psychosocial wellbeing", "psychological wellbeing"),
    "school wellbeing": ("school wellbeing", "school wellness", "whole school wellbeing"),
    "teacher training": ("teacher training", "teacher education", "training of teachers"),
    "parent education": ("parent education", "parent guidance", "parent resource"),
    "adolescent health": ("adolescent health", "teen health", "youth health"),
}

RESEARCH_QUERIES: tuple[str, ...] = (
    "adolescent mental health",
    "teen anxiety",
    "teen depression",
    "adolescent stress",
    "school mental health",
    "bullying intervention",
    "cyberbullying intervention",
    "adolescent sleep",
    "adolescent wellbeing",
    "teacher intervention adolescent mental health",
    "parent intervention adolescent mental health",
)

AUDIENCE_DISCOVERY_TERMS: tuple[str, ...] = (
    "parent guide",
    "parenting adolescents",
    "communication guide",
    "bullying guide",
    "internet safety",
    "digital wellness",
    "school mental health",
    "classroom intervention",
    "bullying prevention",
    "teacher wellbeing",
    "adolescent behaviour management",
)

REQUIRED_CONDITION_PROFILES: tuple[str, ...] = (
    "Depression",
    "Anxiety",
    "Stress",
    "Burnout",
    "Loneliness",
    "Grief",
    "Emotional Regulation",
    "Bullying",
    "Cyberbullying",
    "Peer Pressure",
    "Social Isolation",
    "ADHD",
    "Autism",
    "Learning Difficulties",
    "Sleep Disorders",
    "Gaming Addiction",
    "Internet Addiction",
    "Substance Abuse",
    "Self Harm",
    "Suicide Prevention",
    "Exam Stress",
    "School Refusal",
    "Performance Anxiety",
    "Anger",
    "Risk Taking",
)


def classify_topic(text: str) -> tuple[str | None, str | None]:
    lowered = text.lower()
    topic_aliases = [
        (topic, alias)
        for topic, aliases in TOPIC_ALIASES.items()
        for alias in aliases
    ]
    for topic, alias in sorted(topic_aliases, key=lambda item: len(item[1]), reverse=True):
        if alias in lowered:
            return topic, alias
    return None, None
